# Generated by Django 3.0.6 on 2020-10-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='firstName',
            field=models.CharField(default='', max_length=50, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lastName',
            field=models.CharField(default='', max_length=50, verbose_name='last name'),
        ),
    ]
