# Generated by Django 3.1.1 on 2020-09-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('place_id', models.CharField(max_length=200)),
                ('formatted_address', models.CharField(blank=True, max_length=200)),
                ('rating', models.CharField(blank=True, max_length=200)),
                ('business_status', models.CharField(blank=True, max_length=200)),
                ('lat', models.CharField(blank=True, max_length=200)),
                ('lng', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(blank=True, max_length=200)),
                ('placeType', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
