# Generated by Django 3.1.1 on 2020-10-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0003_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='keys',
            name='apiKey',
            field=models.CharField(max_length=200),
        ),
    ]
